bug:
  - head-branch: ["bug/*"]

enhancement:
  - head-branch: ["feature/*"]

dependencies:
  - changed_files:
      - any-glob-to-any-file: ["package.json", "package-lock.json"]

github_actions:
  - changed_files:
      - any-glob-to-any-file: [".github/workflows/*.yaml"]
