name: Check Code Style

on:
  pull_request:
    branches:
      - $default_branch

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile black"
          requirements-files: "requirements.txt"

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Installing Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Running Pylint
        run: pylint .
