name: Check Dependencies

on:
  pull_request:
    branches:
      - $default_branch

jobs:
  find:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.find-python.outputs.result }}
      web: ${{ steps.find-web.outputs.result }}
    steps:
      - id: find-python
        run: echo "result=${{ hashFiles('**.py') }}" >> "$GITHUB_OUTPUT"
      - id: find-web
        run: echo "result=${{ hashFiles('**.cjs, **.css, **.html, **.html.jinja, **.js, **.json, **.jsx, **.md, **.scss, **.ts, **.tsx, **.yaml, **.yml') }}" >> "$GITHUB_OUTPUT"

  pip:
    if: needs.find.outputs.python
    needs: find
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          if [[ -f requirements.txt ]]; then
              pip install -r requirements.txt --platform manylinux2014_x86_64 --only-binary=":all:" --target=dependencies
          else
              echo "requirements.txt not found"
          fi

  npm:
    if: needs.find.outputs.web
    needs: find
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: |
          if [[ -f package.json && -f package-lock.json ]]; then
              npm install
          else
              echo "package.json and/or package-lock.json not found"
          fi
