name: Check Code Style

on:
  pull_request:
    branches:
      - $default_branch

jobs:
  find:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.find-python.outputs.result }}
      web: ${{ steps.find-web.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - id: find-python
        run: echo "result=${{ hashFiles('**.py') }}" >> "$GITHUB_OUTPUT"
      - id: find-web
        run: echo "result=${{ hashFiles('**.cjs, **.css, **.html, **.html.jinja, **.js, **.json, **.jsx, **.md, **.scss, **.ts, **.tsx, **.yaml, **.yml') }}" >> "$GITHUB_OUTPUT"

  black:
    if: needs.find.outputs.python
    needs: find
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  isort:
    if: needs.find.outputs.python
    needs: find
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile black"
          requirements-files: "requirements.txt"

  prettier:
    if: needs.find.outputs.web
    needs: find
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Installing Prettier
        run: npm install --global prettier
      - name: Running Prettier
        run: prettier --check .

  pylint:
    if: needs.find.outputs.python
    needs: find
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Installing Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Running Pylint
        run: pylint .
