name: All Status Checks

on:
  pull_request:
    branches: main
  workflow_call:

env:
  NODE_AUTH_TOKEN: ${{ secrets.FURY_TOKEN }}

jobs:
  code-style-prettier:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: ${{ secrets.FURY_URL }}
      - run: npm clean-install
      - run: npx prettier --check .

  dependencies-npm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: ${{ secrets.FURY_URL }}
      - run: npm clean-install
