name: All Status Checks

on:
  pull_request:
    branches: main
  workflow_call:

jobs:
  code-style-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure .npmrc exists and is configured
        run: |
          if [ ! -f ".npmrc" ]; then
            echo "registry=https://npm-proxy.fury.io/situdevelopment/" > .npmrc
            echo "//npm-proxy.fury.io/situdevelopment/:_authToken=${FURY_TOKEN}" >> .npmrc
          else
            # If .npmrc exists, replace the existing ${FURY_TOKEN} placeholder or value.
            # This does not happen in the github action for node setup.
            sed -i "s|//npm-proxy.fury.io/situdevelopment/:_authToken=.*|//npm-proxy.fury.io/situdevelopment/:_authToken=${FURY_TOKEN}|g" .npmrc
          fi
          echo "Contents of .npmrc:"
          cat .npmrc
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm install prettier
      - run: npx prettier --check .

  dependencies-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure .npmrc exists and is configured
        run: |
          if [ ! -f ".npmrc" ]; then
            echo "registry=https://npm-proxy.fury.io/situdevelopment/" > .npmrc
            echo "//npm-proxy.fury.io/situdevelopment/:_authToken=${FURY_TOKEN}" >> .npmrc
          else
            # If .npmrc exists, replace the existing ${FURY_TOKEN} placeholder or value.
            # This does not happen in the github action for node setup.
            sed -i "s|//npm-proxy.fury.io/situdevelopment/:_authToken=.*|//npm-proxy.fury.io/situdevelopment/:_authToken=${FURY_TOKEN}|g" .npmrc
          fi
          echo "Contents of .npmrc:"
          cat .npmrc
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm clean-install
