name: All Status Checks

on:
  pull_request:
    branches: main
  workflow_call:

jobs:
  code-style-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm install prettier
      - run: npx prettier --check .

  dependencies-npm:
    runs-on: ubuntu-latest
    env:
      FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Ensure .npmrc exists and is configured
        run: |
          if [ ! -f ".npmrc" ]; then
            echo "registry=https://npm-proxy.fury.io/situdevelopment/"
            echo "//npm-proxy.fury.io/situdevelopment/:_authToken=${FURY_TOKEN}" > .npmrc
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm clean-install
