name: Check Dependencies

on:
  - pull_request
  - workflow_call

jobs:
  fetch-properties:
    uses: ./.github/workflows/fetch-properties.yaml

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm clean-install

  pip:
    if: ${{ fromJSON(needs.fetch-properties.outputs.properties).Python == 'Yes' }}
    needs: fetch-properties
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [ ! -f requirements.txt ]; then
            echo "No requirements.txt found"
            exit 0
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # trailing zero
          cache: pip
      - run: pip install -r requirements.txt

  poetry:
    if: ${{ fromJSON(needs.fetch-properties.outputs.properties).Python == 'Yes' }}
    needs: fetch-properties
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [ ! -f poetry.lock ]; then
            echo "No poetry.lock found"
            exit 0
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # trailing zero
          cache: poetry
      - run: pipx install poetry
      - run: poetry install
