name: Check Dependencies

on:
  - pull_request
  - workflow_call

jobs:
  fetch-properties:
    uses: ./.github/workflows/fetch-properties.yaml

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm clean-install

  pip:
    if: ${{ fromJSON(needs.fetch-properties.outputs.properties).Python == 'Yes' }} && hashFiles("requirements.txt")
    needs: fetch-properties
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: pip
      - run: pip install -r requirements.txt

  poetry:
    if: ${{ fromJSON(needs.fetch-properties.outputs.properties).Python == 'Yes' }} && hashFiles("poetry.lock")
    needs: fetch-properties
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: poetry

      - uses: actions/checkout@v4
      - run: pipx install poetry
      - run: poetry install
