name: Check Code Style

on:
  pull_request:
    branches: main
  workflow_call:
    inputs:
      python-root:
        description: The root directory of the Python project
        required: false
        default: .
        type: string

jobs:
  fetch-properties:
    uses: ./.github/workflows/fetch-properties.yaml

  black:
    if: ${{ fromJSON(needs.fetch-properties.outputs.properties).Python == 'Yes' }}
    needs: fetch-properties
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          src: ${{ inputs.python-root }}

  isort:
    if: ${{ fromJSON(needs.fetch-properties.outputs.properties).Python == 'Yes' }}
    needs: fetch-properties
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # trailing zero
          cache: poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - uses: isort/isort-action@v1
        with:
          configuration: --check-only --diff
          sort-paths: ${{ inputs.python-root }}

  mypy:
    # Do not run for Dependabot PRs as it's fragile and may block automatic merging.
    if: ${{ github.actor != 'dependabot[bot]' && fromJSON(needs.fetch-properties.outputs.properties).Python == 'Yes' }}
    needs: fetch-properties
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # trailing zero
          cache: poetry
      - run: poetry install
      - run: source $(poetry env info --path)/bin/activate
      - run: mypy ${{ inputs.python-root }}

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm clean-install
      - run: npx prettier --check .

  pylint:
    # Do not run for Dependabot PRs as it's fragile and may block automatic merging.
    if: ${{ github.actor != 'dependabot[bot]' && fromJSON(needs.fetch-properties.outputs.properties).Python == 'Yes' }}
    needs: fetch-properties
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # trailing zero
          cache: poetry
      - run: poetry install
      - run: source $(poetry env info --path)/bin/activate
      - run: pylint --exit-zero ${{ inputs.python-root }}
