name: Dependabot Auto Merge

on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_AUTO_MERGE }}
