name: Fetch Properties

on:
  workflow_call:
    outputs:
      properties:
        description: "Properties JSON"
        value: ${{ jobs.fetch-properties.outputs.properties }}

jobs:
  fetch-properties:
    env:
      GH_TOKEN: ${{ github.token }}
    name: Generate output
    runs-on: ubuntu-latest
    outputs:
      properties: ${{ steps.fetch-properties.outputs.properties }}
    steps:
      - id: fetch-properties
        run: |
          properties=$(gh api /repos/${{ github.repository }}/properties/values --jq 'map({(.property_name): .value}) | add')
          echo "properties=${properties}" >> "$GITHUB_OUTPUT"
