name: Label Pull Requests

on:
  - pull_request_target
  - workflow_call

jobs:
  labeller:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeller.yaml
          sync-labels: true
