name: Label Pull Requests

on:
  - pull_request
  - workflow_call

jobs:
  labeller:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@v6
        with:
          configuration-path: .github/labeller.yaml
          sync-labels: true
