name: Python Status Checks

on:
  workflow_call:
    inputs:
      python-root:
        description: The root directory of the Python project
        required: true
        type: string
      run-tests:
        description: Whether to run tests
        required: false
        type: boolean
        default: false
      test-command:
        description: The command(s) used to run tests
        required: false
        type: string
        default: pytest --quiet --pythonwarnings=ignore

jobs:
  code-style-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          src: ${{ inputs.python-root }}

  code-style-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # trailing zero
          cache: poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - uses: isort/isort-action@v1
        with:
          configuration: --check-only --diff
          sort-paths: ${{ inputs.python-root }}

  dependencies-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # trailing zero
          cache: poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install

  linting-mypy:
    # Do not run for Dependabot PRs as it's fragile and may block automatic merging.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # trailing zero
          cache: poetry
      - run: poetry install
      - run: source $(poetry env info --path)/bin/activate && mypy ${{ inputs.python-root }}

  linting-pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # trailing zero
          cache: poetry
      - run: poetry install
      - run: source $(poetry env info --path)/bin/activate && pylint --exit-zero ${{ inputs.python-root }}

  testing-pytest:
    # Do not run for Dependabot PRs as it's fragile and may block automatic merging.
    if: ${{ github.actor != 'dependabot[bot]' && inputs.run-tests }}
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file from `testing` Environment
        run: |
          echo '${{ toJson(secrets) }}' \
            | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .devcontainer/.env
          echo 'GITHUB_ACTIONS=true' >> .devcontainer/.env
      - name: Pytest
        uses: devcontainers/ci@v0.3.1900000349
        with:
          runCmd: ${{ inputs.test-command }}
