name: Status Checks

on: pull_request

jobs:
  code-style:
    runs-on: ubuntu-latest
    uses: SituDevelopment/.github/.github/workflows/check-code-style.yaml@main

  dependencies:
    runs-on: ubuntu-latest
    uses: SituDevelopment/.github/.github/workflows/check-dependencies.yaml@main
