name: TypeScript Status Checks

on: workflow_call

jobs:
  linting-tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm-proxy.fury.io/situdevelopment/"
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/.npmrc') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm clean-install
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      - run: npx tsc --noEmit
