name: TypeScript Status Checks

on: workflow_call

jobs:
  linting-tsc:
    runs-on: ubuntu-latest
    env:
      FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Ensure .npmrc exists and is configured
        run: |
          if [ ! -f ".npmrc" ]; then
            echo "registry=https://npm-proxy.fury.io/situdevelopment/"
            echo "//npm-proxy.fury.io/situdevelopment/:_authToken=${FURY_TOKEN}" > .npmrc
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm clean-install
      - run: npx tsc --noEmit
